modLoader="javafml"
loaderVersion="0"

license="MIT"
issueTrackerURL="https://github.com/virtual-aerotech/axetweak/issues"
[[mods]]
    modId="axetweak"
    version="1.0.0"
    displayTest="MATCH_VERSION"

    logoFile="axetweak.png"
    displayName="Axe Tweak"
    description='''Tweaks vanilla axes' right-clicking behaviour. Now it requires to press Shift+Right-click to strip blocks.'''
    authors="Amelia Blackheart"

[[dependencies.axetweak]]
    modId="forge"
    mandatory=true
    versionRange="0"
    ordering="NONE"
    side="BOTH"
[[dependencies.axetweak]]
    modId="minecraft"
    mandatory=true
    versionRange="1.20.4"
    ordering="NONE"
    side="BOTH"
